name: Validate Deployment Templates
on: [push, pull_request, workflow_dispatch]

env:
    refArmttk: ddca5696ebd7e718184fe65ff0be17bb06ccdd25
    refJavaee: c87108cc7d591a1d1eb0a7eb7aff4bc96dc1a0da

jobs:
  validate:
    name: Validate Deployment Templates
    runs-on: ubuntu-latest
    steps:
      - name: Check out rhel-jboss-templates
        uses: actions/checkout@v2
        with:
          path: rhel-jboss-templates

      - name: Checkout azure-javaee-iaas
        uses: actions/checkout@v2
        with:
          repository: Azure/azure-javaee-iaas
          path: azure-javaee-iaas
          ref: ${{ env.refJavaee }}

      - name: Checkout arm-ttk
        uses: actions/checkout@v2
        with:
          repository: Azure/arm-ttk
          path: arm-ttk
          ref: ${{ env.refArmttk }}
      
      - name: Build azure-javaee-iaas
        run: mvn -DskipTests clean install --file azure-javaee-iaas/pom.xml
          
      - name: Perform validation
        run: |
          cd rhel-jboss-templates
          ./validateOffers.sh
